CREATE TABLE BOOKING (
    BookingID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
    , GuestID INTEGER NOT NULL
    , RoomID INTEGER NOT NULL
    , StaffID INTEGER NOT NULL
    , CheckInDT DATETIME NOT NULL
    , CheckOutDT DATETIME NOT NULL
    , IsDeleted BOOL NOT NULL
    , FOREIGN KEY(GuestID)
        REFERENCES GUEST(GuestID)
    , FOREIGN KEY(RoomID)
        REFERENCES ROOM(RoomID)
    , FOREIGN KEY(StaffID)
        REFERENCES STAFF(StaffID)
);