--
-- File generated with SQLiteStudio v3.4.17 on Mon Jun 30 11:31:11 2025
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: BOOKING
CREATE TABLE IF NOT EXISTS BOOKING (
    BookingID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
    , GuestID INTEGER NOT NULL
    , RoomID INTEGER NOT NULL
    , StaffID INTEGER NOT NULL
    , CheckInDT DATETIME NOT NULL
    , CheckOutDT DATETIME NOT NULL
    , IsDeleted BOOL NOT NULL
    , FOREIGN KEY(GuestID)
        REFERENCES GUEST(GuestID)
    , FOREIGN KEY(RoomID)
        REFERENCES ROOM(RoomID)
    , FOREIGN KEY(StaffID)
        REFERENCES STAFF(StaffID)
);

-- Table: GUEST
CREATE TABLE IF NOT EXISTS GUEST (
    GuestID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
    , FName VARCHAR(100) NOT NULL
    , MName VARCHAR(100) NULL
    , LName VARCHAR(100) NOT NULL
    , Email VARCHAR(60) NULL
    , PhoneNumber VARCHAR(40) NULL
    , Proof_ID_Type VARCHAR(60) NOT NULL
    , Proof_ID_Number VARCHAR(60) NOT NULL
    , Street VARCHAR(60) NOT NULL
    , Barangay VARCHAR(60) NULL
    , Zip VARCHAR(60) NULL
    , City VARCHAR(60) NOT NULL
    , Gender VARCHAR(30) NULL
    , IsDeleted BOOL NOT NULL
);

-- Table: ROOM
CREATE TABLE IF NOT EXISTS ROOM (
    RoomID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
    , RoomType VARCHAR(100) NOT NULL
    , BedType VARCHAR(100) NOT NULL
    , RoomCapacity INTEGER NOT NULL
    , Status VARCHAR(100) NOT NULL
    , Base_Price DECIMAL(10, 3) NOT NULL
);

-- Table: STAFF
CREATE TABLE IF NOT EXISTS STAFF (
    StaffID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
    , FName VARCHAR(100) NOT NULL
    , MName VARCHAR(50) NULL
    , LName VARCHAR(100) NOT NULL
    , Username VARCHAR(100) NOT NULL
    , Password VARCHAR(100) NOT NULL
    , IsDeleted BOOL NOT NULL 
    , Role VARCHAR(40) NOT NULL
    , Staff_ID INTEGER NULL   
    , FOREIGN KEY(Staff_ID)
        REFERENCES STAFF(StaffID)
);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
