CREATE TABLE ROOM (
    RoomID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
    , RoomType VARCHAR(100) NOT NULL
    , BedType VARCHAR(100) NOT NULL
    , RoomCapacity INTEGER NOT NULL
    , Status VARCHAR(100) NOT NULL
    , Base_Price DECIMAL(10, 3) NOT NULL
);