CREATE TABLE STAFF (
    StaffID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
    , FName VARCHAR(100) NOT NULL
    , MName VARCHAR(50) NULL
    , LName VARCHAR(100) NOT NULL
    , Username VARCHAR(100) NOT NULL
    , Password VARCHAR(100) NOT NULL
    , IsDeleted BOOL NOT NULL 
    , Role VARCHAR(40) NOT NULL
    , Staff_ID INTEGER NULL   
    , FOREIGN KEY(Staff_ID)
        REFERENCES STAFF(StaffID)
);